### ISSUE TITLE
No version specified, and no candidate version available for mariadb-client 

### ISSUE THREAD

**Issue by jverdeyen** [joerocklin/chef-mariadb#2]
I've included the recipes in another recipe:
include_recipe "mariadb::client"
include_recipe "mariadb::ruby"
include_recipe "mariadb::server"

But it seems like the repo isn't added on time.

```

* No version specified, and no candidate version available for mariadb-client
================================================================================
Error executing action `install` on resource 'package[mariadb-client]'
================================================================================


Chef::Exceptions::Package
-------------------------
No version specified, and no candidate version available for mariadb-client


Cookbook Trace:
---------------
/tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:29:in `block in from_file'
/tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:28:in `each'
/tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:28:in `from_file'
/tmp/chef-solo/site-cookbooks/apps/recipes/webapp.rb:7:in `from_file'
/tmp/chef-solo/site-cookbooks/apps/recipes/stats.rb:11:in `from_file'


Resource Declaration:
---------------------
# In /tmp/chef-solo/cookbooks/mariadb/recipes/client.rb

 48:   package mariadb_pack do
 49:     action :install
 50:   end
 51: end



Compiled Resource:
------------------
# Declared in /tmp/chef-solo/cookbooks/mariadb/recipes/client.rb:48:in `block in from_file'

package("mariadb-client") do
  action [:install]
  retries 0
  retry_delay 2
  package_name "mariadb-client"
  cookbook_name :mariadb
  recipe_name "client"
end




================================================================================
Recipe Compile Error in /tmp/chef-solo/site-cookbooks/apps/recipes/stats.rb
================================================================================


Chef::Exceptions::Package
-------------------------
package[mariadb-client] (mariadb::client line 48) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for mariadb-client


Cookbook Trace:
---------------
  /tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:29:in `block in from_file'
  /tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:28:in `each'
  /tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:28:in `from_file'
  /tmp/chef-solo/site-cookbooks/apps/recipes/webapp.rb:7:in `from_file'
  /tmp/chef-solo/site-cookbooks/apps/recipes/stats.rb:11:in `from_file'


Relevant File Content:
----------------------
/tmp/chef-solo/cookbooks/mariadb/recipes/ruby.rb:

 22:  
 23:  node.set['build_essential']['compiletime'] = true
 24:  include_recipe "build-essential"
 25:  include_recipe "mariadb::mariadb_repo"
 26:  include_recipe "mariadb::client"
 27:  
 28:  node['mariadb']['client']['packages'].each do |mariadb_pack|
 29>>   resources("package[#{mariadb_pack}]").run_action(:install)
 30:  end
 31:  
 32:  chef_gem "mysql"
 33:  


[2013-10-10T15:16:27+00:00] ERROR: Running exception handlers
[2013-10-10T15:16:27+00:00] ERROR: Exception handlers complete
[2013-10-10T15:16:27+00:00] FATAL: Stacktrace dumped to /tmp/chef-solo/chef-stacktrace.out
Chef Client failed. 2 resources updated
[2013-10-10T15:16:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.

```

I'm running chef with knife solo.

**Comment by joerocklin** [comment]
What platform are you running on @jverdeyen? I have only used/minimally tested this on CentOS.

**Comment by jverdeyen** [comment]
I'm running on Ubuntu 13.04 minimal, so debian.

When run chef first without the client/sever/.. and only the repo, everything runs ok.
After that on a second run with client/server/.. included is working.
